# Generated by Django 5.1.5 on 2025-02-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='productovariante',
            name='color',
            field=models.CharField(choices=[('Rojo', 'Rojo'), ('Azul', 'Azul'), ('Amarillo', 'Amarillo')], max_length=50, null=True),
        ),
    ]
