# Generated by Django 5.1.5 on 2025-02-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_productovariante_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productovariante',
            name='color',
            field=models.CharField(choices=[('Red', 'Rojo'), ('Blue', 'Azul'), ('Yellow', 'Amarillo')], max_length=50, null=True),
        ),
    ]
