# Generated by Django 5.1.5 on 2025-03-04 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_productovariante_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoSucursal',
        ),
    ]
